codecov:
  require_ci_to_pass: yes
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
codecov:
  token: c74d0652-575f-49a4-b77e-7857f25d42e8


